### ISSUE TITLE
Add Texture Infrastructure (MC).

### ISSUE THREAD

**Issue by Josh194** [Josh194/FMCB#7]
Setup everything necessary in the MC subsystem to allow easy addition of textures to items/blocks (this should be fairly easy to do, a few folders and a couple JSON descriptors will need to added, along with a small bit of Java code).

**Comment by MegaGlub** [comment]
Nearly complete, just lacking cleanup and review

**Comment by Josh194** [comment]
Perfect, I'll finish up my branch, and once that's pulled I'll move to your branch and make sure everything looks good in the code department.
